<?xml version="1.0" encoding="utf-8"?><testsuites><testsuite name="pytest" errors="21" failures="0" skipped="0" tests="21" time="0.286" timestamp="2021-06-30T21:33:14.086418" hostname="DESKTOP-TCMPOAA"><testcase classname="part1_test" name="test_number_of_videos" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_show_all_videos" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_play_video" time="0.003"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_play_video_nonexistent" time="0.002"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_play_video_stop_previous" time="0.002"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_play_video_dont_stop_previous_if_nonexistent" time="0.002"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_stop_video" time="0.002"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_stop_video_twice" time="0.003"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_stop_video_none_playing" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_play_random_video" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_play_random_stops_previous_video" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_show_playing" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_show_nothing_playing" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_pause_video" time="0.002"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_pause_video_show_playing" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_pause_video_play_video" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_pause_already_paused_video" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_pause_video_none_playing" time="0.002"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_continue_video" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_continue_video_not_paused" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase><testcase classname="part1_test" name="test_continue_none_playing" time="0.001"><error message="failed on setup with &quot;ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)&#10;..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)&quot;">ScopeMismatch: You tried to access the 'function' scoped fixture 'base_url' with a 'session' scoped request object, involved factories
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_base_url\plugin.py:22:  def _verify_url(request, base_url)
..\..\..\..\anaconda3\envs\project\lib\site-packages\pytest_tornado\plugin.py:155:  def base_url(request)</error></testcase></testsuite></testsuites>